##################################################
##### DEVELOPMENT ENVIRONMENT           ##########
##################################################

# Public ports:
#  - 8081 -> Neos
#  - 13306 -> maria db (used for Neos)

services:
  #####
  # Laravel (php-fpm)
  laravel:
    build:
      context: .
      dockerfile: ./deployment/local-dev/laravel/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      COMPOSER_CACHE_DIR: '/composer_cache'
      # DB connection
      DB_HOST: 'maria-db'
      DB_PORT: 3306
      DB_PASSWORD: 'laravel'
      DB_USER: 'laravel'
      DB_DATABASE: 'laravel'
      DB_DATABASE_SCRAMBLED: 'laravel_scrambled'

      APP_URL: http://127.0.0.1:8082
      CACHE_DRIVER: redis
      REDIS_HOST: 'redis-cache'
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis

      IMAGOR_SECRET: iruendwsmacki9gu8hdewijsochudjsiuhu
      IMAGOR_SIGNER_TYPE: sha256
      IMAGOR_SIGNER_TRUNCATE: 40

    volumes:
      - ./app/:/app/:cached
      - laravel-storage:/app/storage
      # Explicitly set up Composer cache for faster fetching of packages
      - laravel-composer-cache:/composer_cache:cached
    ports:
      - 8081:8081
      - 9090:9090 # for laravel_scrambled
    depends_on:
      - maria-db
      - redis-cache

  #####
  # assets build (watcher)
  filament-assets:
    build:
      context: .
      dockerfile: ./deployment/local-dev/filament-assets/Dockerfile
    volumes:
      # everything is readonly except the "Public" folder (which contains the build results);
      - ./app/DistributionPackages/MyVendor.AwesomeNeosProject/Resources/Private:/app/src/Private/:cached
      - ./app/DistributionPackages/MyVendor.AwesomeNeosProject/Resources/Public:/app/src/Public/:cached
      ### start: delete on kickstart ###
      # also mount the fusion files of the component library so that tailwind knows all classes
      - ./app/DistributionPackages/Sandstorm.ComponentLibrary/Resources/Private/Fusion:/app/src/Private/Fusion/ComponentLibrary/:ro,cached
      ### end: delete on kickstart ###
      # Explicitly set up Yarn cache for faster fetching of packages
      - yarn-cache:/app/.yarn-cache

  #####
  # Maria DB
  maria-db:
    image: mariadb:10.11
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      DB_DATABASE_SCRAMBLED: 'laravel_scrambled'
      MARIADB_AUTO_UPGRADE: 1
    # use Unicode encoding as default!
    volumes:
      - ./deployment/local-dev/maria-db/createTestingDB.sh:/createTestingDB.sh:cached
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  #####
  # Mailpit (local smtp)
  mailpit:
    image: axllent/mailpit:latest
    hostname: mailpit
    ports:
      - '8025:8025'

  redis-cache:
    image: redis:7
    ports:
      - 16379:6379

volumes:
  neos-assets-node-modules:
  laravel-storage:
  laravel-composer-cache:
    external: true
  yarn-cache:
    external: true

