name: "Run tests"

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Get Composer Cache Directory
        id: cache-composer
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache-composer.outputs.dir }}
          key: ${{ runner.os }}-${{ github.ref_name }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --ignore-platform-reqs

      - name: Run tests
        run: |
          composer test