nodeLinker: node-modules
# use .yarn/cache folder instead of global cache (https://yarnpkg.com/features/caching)
enableGlobalCache: false

# Block installation of packages published less than 14 days ago to reduce supply chain attack exposure
npmMinimalAgeGate: "14d"
