apiVersion: k8s.sandstorm.de/v1alpha1
kind: OneContainerOnePort
metadata:
  namespace: serious-game-staging
  name: app
spec:
  appName: serious-game-staging
  description: 'Sample Laravel Deployment in the Rancher Cluster.'

  hostNames:
    serious-game-staging.cloud.sandstorm.de: []

  node: worker4
  image: ghcr.io/sandstorm/serious-game-legacy/laravel:main

  port: 8081
  # Set to false when a real DNS entry for staging/staging exists
  stagingCertificates: false

  env:
    SHELL_ENV_DISPLAY: 'staging-serious-game'
  extraPodEnvInK8sFormat:
    - name: DB_CONNECTION
      value: "mariadb"
    # DB_HOST matching already
    - name: DB_PORT
      value: "3306"
    - name: DB_USERNAME
      value: "$(DB_USER)"
    # DB_PASSWORD is matching already
    - name: DB_DATABASE
      value: "$(DB_NAME)"

  envFromConfigMaps:
    - db
  envFromSecrets:
    - db
    - laravel-encryption-key
    #- deepl-api-key
    #- sandstorm-maps-api-key

  httpBasicPasswordProtection:
    enabled: true
    secretName: basic-auth

  healthChecks:
    readinessProbe:
      enabled: false

    livenessProbe:
      enabled: false

  redis: persistent

  sso:
    enabled: false

  stopped: false
