apiVersion: k8s.sandstorm.de/v1alpha1
kind: OneContainerOnePort
metadata:
  namespace: myvendor-awesomeneosproject-staging
  name: app
spec:
  appName: myvendor-awesomeneosproject-staging
  description: 'Sample Laravel Deployment in the Rancher Cluster.'

  hostNames:
    myvendor-awesomeneosproject-staging.cloud.sandstorm.de: []

  node: worker4
  image: docker-hub.sandstorm.de/infrastructure/laravel-on-docker-kickstart/laravel:main

  port: 8081
  # Set to false when a real DNS entry for staging/staging exists
  stagingCertificates: false

  env:
    SHELL_ENV_DISPLAY: 'staging-myvendor-awesomeneosproject'
  extraPodEnvInK8sFormat:
    - name: DB_CONNECTION
      value: "mariadb"
    # DB_HOST matching already
    - name: DB_PORT
      value: "3306"
    - name: DB_USERNAME
      value: "$(DB_USER)"
    # DB_PASSWORD is matching already
    - name: DB_DATABASE
      value: "$(DB_NAME)"

  envFromConfigMaps:
    - db
  envFromSecrets:
    - db
    - laravel-encryption-key
    #- deepl-api-key
    #- sandstorm-maps-api-key

#  httpBasicPasswordProtection:
#    enabled: true
#    secretName: basic-auth

  healthChecks:
    readinessProbe:
      enabled: false

    livenessProbe:
      enabled: false

  redis: persistent

  sso:
    enabled: false

  stopped: false
