Sandstorm:
  ComponentLibrary:
    Components:
      Accordion:
        files:
          - 'NodeTypes/Content/Content.Accordion.yaml'
          - 'NodeTypes/Content/Content.Accordion.Item.yaml'
          - 'Resources/Private/Fusion/Integration/Content/Content.Accordion.fusion'
          - 'Resources/Private/Fusion/Integration/Content/Content.Accordion.Item.fusion'
          - 'Resources/Private/Fusion/Presentation/Components/Accordion'
          - 'Resources/Private/Translations/de/NodeTypes/Content/Accordion'
          - 'Resources/Private/Translations/en/NodeTypes/Content/Accordion'
        constraintType: 'Special'
      ButtonWithIcon:
        files:
          - 'NodeTypes/Content/Content.ButtonWithIcon.yaml'
          - 'Resources/Private/Fusion/Integration/Content/Content.ButtonWithIcon.fusion'
          - 'Resources/Private/Translations/de/NodeTypes/Content/ButtonWithIcon.xlf'
          - 'Resources/Private/Translations/en/NodeTypes/Content/ButtonWithIcon.xlf'
      Download:
        files:
          - 'NodeTypes/Content/Content.Download.yaml'
          - 'Resources/Private/Fusion/Integration/Content/Content.Download.fusion'
          - 'Resources/Private/Fusion/Presentation/Components/Download'
          - 'Resources/Private/Translations/de/NodeTypes/Content/Download.xlf'
          - 'Resources/Private/Translations/en/NodeTypes/Content/Download.xlf'
          - 'Tests/Unit/Eel/FileSizeHelperTest.php'
        eelHelpers:
          - 'FileSize'
      Headline:
        files:
            - 'NodeTypes/Content/Content.Headline.yaml'
            - 'Resources/Private/Fusion/Integration/Content/Content.Headline.fusion'
            - 'Resources/Private/Fusion/Presentation/Components/Headline'
            - 'Resources/Private/Translations/de/NodeTypes/Content/Headline.xlf'
            - 'Resources/Private/Translations/en/NodeTypes/Content/Headline.xlf'
      LogoBar:
        files:
          - 'NodeTypes/Content/Content.LogoBar.yaml'
          - 'NodeTypes/Content/Content.LogoBar.Slide.yaml'
          - 'Resources/Private/Fusion/Integration/Content/Content.LogoBar.fusion'
          - 'Resources/Private/Fusion/Integration/Content/Content.LogoBar.Slide.fusion'
          - 'Resources/Private/Fusion/Presentation/Components/LogoBar'
          - 'Resources/Private/Translations/de/NodeTypes/Content/LogoBar'
          - 'Resources/Private/Translations/de/NodeTypes/Content/LogoBar.xlf'
          - 'Resources/Private/Translations/en/NodeTypes/Content/LogoBar'
          - 'Resources/Private/Translations/en/NodeTypes/Content/LogoBar.xlf'
        jsDependencies:
          - 'swiper@^10.2.0'
        alpineComponent: true
        constraintType: "Special"
      Spacer:
        files:
          - 'NodeTypes/Content/Content.Spacer.yaml'
          - 'Resources/Private/Fusion/Integration/Content/Content.Spacer.fusion'
          - 'Resources/Private/Fusion/Presentation/Components/Spacer'
          - 'Resources/Private/Translations/de/NodeTypes/Content/Spacer.xlf'
          - 'Resources/Private/Translations/en/NodeTypes/Content/Spacer.xlf'
