Neos:
  Fusion:
    defaultContext:
      'Sandstorm.ComponentLibrary.FileSize': 'Sandstorm\ComponentLibrary\Eel\Helper\FileSizeHelper'
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Sandstorm.ComponentLibrary': [ 'NodeTypes/*' ]
    fusion:
      autoInclude:
        Sandstorm.ComponentLibrary: true
