build_assets:
  stage: compile_resources
  rules:
    - when: always
  image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
  needs: []
  interruptible: true
  script:
    - cd app
    - COMPOSER_CACHE_DIR=.composer-cache composer install --ignore-platform-reqs
    # example for including font-awesome
    #- npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    #- npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_AUTH_TOKEN
    - yarn
    - yarn build
  cache:
    key: MyVendor.AwesomeNeosProject__composer
    paths:
      - app/.composer-cache
      - app/node_modules/

  artifacts:
    expire_in: 7 days
    paths:
      - app/public/build/

