
package_app_production:
  stage: build
  rules:
    - when: always
    - if: '$CI_COMMIT_TAG'
      when: always
  image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
  needs:
    - build_assets
  cache:
    key: MyVendor.AwesomeNeosProject__composer
    paths:
      - app/.composer-cache
  interruptible: true
  script:
    - cd app
    # NOTE: for E2E tests we HAVE also to install DEV dependencies; otherwise we won't be able to run behavioral tests then.
    - COMPOSER_CACHE_DIR=.composer-cache composer install --dev --ignore-platform-reqs
    - cd ..

    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/laravel:main || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/laravel:main -t $CI_REGISTRY_IMAGE/laravel:$CI_COMMIT_REF_SLUG -f deployment/production/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/laravel:$CI_COMMIT_REF_SLUG

deploy_production:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    #- if: '$CI_COMMIT_TAG'
    #  when: always
  image:
    name: bitnami/kubectl:1.15.0
    entrypoint: ['']
  needs:
    - package_app_production
    - test
  environment:
    name: production
  script:
    - eval $(ssh-agent -s)
    - chmod 600 $SSH_PRIVATE_DEPLOY_KEY
    - ssh-add $SSH_PRIVATE_DEPLOY_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -p 29418 -H your-domain.de >> ~/.ssh/known_hosts

    # deploy the actual application
    - scp -P 29418 deployment/production/docker-compose-prod.yml deploy@your-domain.de:~/your-project/docker-compose.yml
    - scp -P 29418 deployment/production/vector.flow.yaml deploy@your-domain.de:~/your-project/vector.flow.yaml
    # NOTE: to ensure vector always uses the most up-to-date config, we restart vector after deployment (because
    # vector.flow.yaml is *mounted* into the container)
    - |
      ssh -p 29418 deploy@your-domain.de "
        docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY &&
        cd your-project &&
        sed -ri 's/DOCKER_IMAGE_VERSION/$CI_COMMIT_REF_NAME/g' docker-compose.yml &&
        ([ -f .env ] || { echo 'ERROR: You manually need to create a .env file with secrets first.'; exit 1; }) &&
        docker compose pull &&
        docker compose up -d &&
        docker compose restart vector
      "
