php_code_analysis:
  image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
  stage: test
  rules:
    - when: always
  needs: []
  dependencies: []
  interruptible: true
  allow_failure: true
  cache:
    key: MyVendor.AwesomeNeosProject__composer
    paths:
      - app/.composer-cache
  script:
    - cd app
    - COMPOSER_CACHE_DIR=.composer-cache composer install --ignore-platform-reqs
    - ./vendor/bin/phpstan analyse --no-progress --memory-limit 1G --error-format table

test:
  stage: test
  image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
  # rules:
  # - run on merge_requests when triggered manually as part of the pipeline
  # - always run on main branch pipelines and tag pipelines
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG'
      when: always
  interruptible: true
  # we're running this job inside the production image we've just built previously
  cache:
    key: MyVendor.AwesomeNeosProject__composer
    paths:
      - app/.composer-cache
  script:
    - cd app
    - COMPOSER_CACHE_DIR=.composer-cache composer install --ignore-platform-reqs
    - ./vendor/bin/pest --ci --log-junit=test-results/pest.xml
    - echo "CI tests finished"
  allow_failure: true
  artifacts:
    expire_in: 5 days
    when: always
    paths:
      - test-results
    reports:
      junit: test-results/pest.xml

#code_metrics:
#  stage: quality-ci
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
#      when: always
#    - if: '$CI_COMMIT_TAG'
#      when: never
#  needs: []
#  extends:
#    - .code-metrics-template
#  variables:
#    SOURCE_ROOT: app/DistributionPackages
#    IGNORE_PATTERN: "bundle\\.(css|js)"
