php_code_analysis:
  image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
  stage: test
  rules:
    - when: always
  needs: []
  dependencies: []
  interruptible: true
  cache:
    key: MyVendor.AwesomeNeosProject__composer
    paths:
      - app/.composer-cache
  script:
    - cd app
    - COMPOSER_CACHE_DIR=.composer-cache composer install --ignore-platform-reqs
    - ./vendor/bin/phpstan analyse --no-progress --memory-limit 1G --error-format table

test:
  stage: test
  image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
  # rules:
  # - run on merge_requests when triggered manually as part of the pipeline
  # - always run on main branch pipelines and tag pipelines
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_OPEN_MERGE_REQUESTS'
      when: manual
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG'
      when: always
  interruptible: true
  # we're running this job inside the production image we've just built previously
  cache:
    key: MyVendor.AwesomeNeosProject__composer
    paths:
      - app/.composer-cache
  script:
    - cd app
    - COMPOSER_CACHE_DIR=.composer-cache composer install --ignore-platform-reqs
    - ./vendor/bin/pest --ci --log-junit=test-results/pest.xml
    - echo "CI tests finished"
  variables:
    # service mariadb
    MYSQL_USER: "ci_user"
    MYSQL_PASSWORD: "ci_db_password"
    MYSQL_DATABASE: "ci_test"
    # otherwise service will not start
    MARIADB_RANDOM_ROOT_PASSWORD: "yes"

    # laravel
    # INSECURE; for local dev only
    APP_KEY: base64:+cg1qRwOrn6qExb0tCCUJpKCemMY6PcZEax9qhcObbs=
    DB_CONNECTION: mariadb
    DB_HOST: mariadb
    DB_PORT: 3306
    DB_USERNAME: ${MYSQL_USER}
    DB_PASSWORD: ${MYSQL_PASSWORD}
    DB_DATABASE: ${MYSQL_DATABASE}
    CACHE_STORE: redis
    REDIS_HOST: redis
    REDIS_PORT: 6379
    QUEUE_CONNECTION: redis
  services:
    - name: mariadb:10.11
    - name: redis:7
  artifacts:
    expire_in: 5 days
    when: always
    paths:
      - app/test-results
    reports:
      junit: app/test-results/pest.xml

#code_metrics:
#  stage: quality-ci
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
#      when: always
#    - if: '$CI_COMMIT_TAG'
#      when: never
#  needs: []
#  extends:
#    - .code-metrics-template
#  variables:
#    SOURCE_ROOT: app/DistributionPackages
#    IGNORE_PATTERN: "bundle\\.(css|js)"
