@playwright
@fixtures
@EventList
Feature: Event list with filter

    Background:
        Given I have a site for Site Node "site" with name "Website"
        Given I have the following nodes:
            | Identifier                           | Path                                                                      | Node Type                                                 | Properties                                                                                                                                                                                                                                                                                                                                                                                                                                      | HiddenInIndex | Language |
            | 034da82d-a2cc-42f7-a057-18ced6e567f0 | /sites                                                                    | unstructured                                              | []                                                                                                                                                                                                                                                                                                                                                                                                                                              | false         | de       |
            | 9f3c8992-4317-45af-b426-2ab6076849c0 | /sites/site                                                               | MyVendor.AwesomeNeosProject:Document.StartPage            | {"uriPathSegment":"awesomeneosproject","title":"AwesomeNeosProject","privacyPage":"b9d32958-9bc0-4502-bdd2-274b54f1777e","isCornerstone":false,"facebookLink":"https:\/\/www.facebook.com\/","twitterLink":"https:\/\/twitter.com\/","instagramLink":"https:\/\/www.instagram.com\/","youtubeLink":"https:\/\/www.youtube.com\/","mastodonLink":"https:\/\/mastodon.social"}                                                                    | false         | de       |
            | 5dd01e56-3d21-4127-b1ba-99e5603571ea | /sites/site/node-ew3btfa0bg3rm                                            | MyVendor.AwesomeNeosProject:Document.Blog                 | {"uriPathSegment":"blog","title":"Blog","isCornerstone":false}                                                                                                                                                                                                                                                                                                                                                                                  | false         | de       |
            | a12e12fd-57b3-42a7-a4c4-bc763d96667e | /sites/site/node-ew3btfa0bg3rm/tags/node-abjc143jg57jx                    | MyVendor.AwesomeNeosProject:Document.Blog.Tag             | {"uriPathSegment":"some-tag","title":"Some Tag","isCornerstone":false}                                                                                                                                                                                                                                                                                                                                                                          | false         | de       |
            | 0f5c04ed-2975-476f-8854-31a4c4d4bffc | /sites/site/node-ew3btfa0bg3rm/tags/node-bda0qyjey9ov2                    | MyVendor.AwesomeNeosProject:Document.Blog.Tag             | {"uriPathSegment":"another-tag","title":"Another Tag","isCornerstone":false}                                                                                                                                                                                                                                                                                                                                                                    | false         | de       |
            | 8f24e608-f8e7-452c-9161-257f03e3072b | /sites/site/node-7226s0m2aghb3                                            | MyVendor.AwesomeNeosProject:Document.Events               | {"uriPathSegment":"events","isCornerstone":false,"title":"Events"}                                                                                                                                                                                                                                                                                                                                                                              | false         | de       |
            | 73fd9c67-7942-456b-b80d-d4a14b3aa515 | /sites/site/node-7226s0m2aghb3/main/node-qf7gfmbo5uxlb                    | MyVendor.AwesomeNeosProject:Content.SectionWithBackground | {"backgroundColor":"white","padding":"default"}                                                                                                                                                                                                                                                                                                                                                                                                 | false         | de       |
            | 887a64f5-ca8e-492c-a463-c090a6554e45 | /sites/site/node-7226s0m2aghb3/main/node-qf7gfmbo5uxlb/node-2j7qlpxpc9ug0 | MyVendor.AwesomeNeosProject:Content.Headline              | {"title":"<h1>Events<\/h1>"}                                                                                                                                                                                                                                                                                                                                                                                                                    | false         | de       |
            | 7dd0e1ae-68fb-4a5d-9793-867ceb06e0c4 | /sites/site/node-7226s0m2aghb3/main/node-qf7gfmbo5uxlb/node-q8wm933ephylt | MyVendor.AwesomeNeosProject:Content.Events.List           | {"amountOfEvents":"3"}                                                                                                                                                                                                                                                                                                                                                                                                                          | false         | de       |
            | 8a321e57-a4e3-42ef-8ddc-8fb4805000ae | /sites/site/node-7226s0m2aghb3/node-zb44crcrkmkqx                         | MyVendor.AwesomeNeosProject:Document.Events.Event         | {"uriPathSegment":"kickstarter-demo","isCornerstone":false,"title":"Kickstarter Demo","date":{"date":"2128-03-05 00:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"},"location":"Tatzberg 47, 01307 Dresden","dateUntil":{"date":"2024-05-31 00:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"}}                                                                                                                       | false         | de       |
            | 6a8a7edf-6050-4c60-932c-a6246ecece4f | /sites/site/node-7226s0m2aghb3/node-o6cnid9sd2hhq                         | MyVendor.AwesomeNeosProject:Document.Events.Event         | {"uriPathSegment":"kickstarter-demo-1","isCornerstone":false,"title":"Kickstarter Demo 2","date":{"date":"2128-04-19 00:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"},"location":"","timeFrom":{"date":"2023-03-01 11:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"},"timeTo":{"date":"2023-03-01 13:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"},"tags":["a12e12fd-57b3-42a7-a4c4-bc763d96667e"]} | false         | de       |
            | cf2c5fbb-8372-4894-bbcf-973b175add79 | /sites/site/node-7226s0m2aghb3/node-fn9cbta8eosld                         | MyVendor.AwesomeNeosProject:Document.Events.Event         | {"uriPathSegment":"kickstarter-demo-1-1","isCornerstone":false,"title":"Kickstarter Demo 3","date":{"date":"2128-05-16 00:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"},"location":"Slack-Huddle","timeFrom":{"date":"2023-03-01 11:00:00.000000","timezone":"UTC","dateFormat":"Y-m-d H:i:s.u"},"timeTo":null,"tags":["0f5c04ed-2975-476f-8854-31a4c4d4bffc"]}                                                                  | false         | de       |

        And I accepted the Cookie Consent

    Scenario: Filter events
        Given I access the URI path "/events"
        Then the page title should be "Events - Website"
        And I see 3 events

        When I click on the filter button
        And I click on the filter with title "Some Tag"
        Then I wait for the url to be "/events?tags=some-tag"
        And I see 1 events

        When I click on the filter button
        And I click on the filter with title "Another Tag"
        Then I wait for the url to be "/events?tags=some-tag%2Canother-tag"
        And I see 2 events

        When I click on the filter button
        And I click on the filter with title "Another Tag"
        Then I wait for the url to be "/events?tags=some-tag"
        And I see 1 events

        Then I delete all filter
        And I wait for the url to be "/events"
        And I see 3 events
