name: Package App Staging

on:
  push:
    branches: [ main ]
  pull_request:
  # For running on tags (releases)
  tags:
    - '*'
  workflow_dispatch:

jobs:
  package_app_staging:
    name: Package App Staging
    runs-on: [self-hosted, linux]
    # Always run this job, including on tags
    container:
      image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v4
    needs: build_assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: app/.composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install PHP dependencies including dev dependencies
      - name: Install Composer dependencies
        run: |
          cd app
          COMPOSER_CACHE_DIR=.composer-cache composer install --dev --ignore-platform-reqs
          cd ..

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CI_REGISTRY || 'ghcr.io' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Determine ref slug for Docker tag (similar to CI_COMMIT_REF_SLUG)
      - name: Get ref slug
        id: get-ref-slug
        run: |
          REF_SLUG=$(echo "${{ github.ref_name }}" | sed -e 's/[^a-zA-Z0-9]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "REF_SLUG=$REF_SLUG" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deployment/staging/Dockerfile
          push: true
          tags: ${{ vars.CI_REGISTRY_IMAGE || format('ghcr.io/{0}', github.repository) }}/laravel:${{ steps.get-ref-slug.outputs.REF_SLUG }}
          cache-from: ${{ vars.CI_REGISTRY_IMAGE || format('ghcr.io/{0}', github.repository) }}/laravel:main
